### ISSUE TITLE
error for build first bot

### ISSUE THREAD

**Issue by flydsc** [salesforce/Converse#10]
Hi,

Thank you for your hard work on this tool framework.

I was just following the tutorial, Build your first bot with Converse. For the first method, I found some error messages when I got to step 4.

The  flask UI was successfully running, but always got the error `POST http://0.0.0.0:9002/process 500 (INTERNAL SERVER ERROR)` from the browser console, and an error in the terminal:

```
debug_error_string = "{"created":"@1649268538.463046000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1649268538.463042000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
```

any idea about how this would happen?

Do I need to start any server before running the file dial_backend.py ?

**Comment by tianxie-sf** [comment]
Hi @flydsc, I am sorry that I didn't make it clear how to the NLU services. 
You can start the NLU services by
```
docker run --name myintent -p 9001:9001 converseallresearch/intent:0.1
docker run --name myner -p 50051:50051 converseallresearch/ner:0.1
```
I will update the readme soon.
